export const PathRouteConstants = {
    indexRoute: '',
    loginRoute: '/login',
    changePasswordRoute: '/change-password',
    productsRoute: '/products',
    productDetailsRoute: '/products/:productSlug',
    productInsertRoute: '/products/insert',
    ordersRoute: '/orders',
    orderDetailsRoute: '/orders/:orderId',
    reviewsRoute: '/reviews',
    reviewDetailsRoute: '/reviews/:reviewSlug',
    reviewInsertRoute: '/reviews/insert',
    tipsRoute: '/tips',
    tipDetailsRoute: 'tips/:tipSlug',
    tipInsertRoute: '/tips/insert',
    policiesRoute: '/policies',
    policyDetailsRoute: '/policies/:type',
    newsListRoute: '/news',
    newsDetailsRoute: '/news/:newsSlug',
    newsInsertRoute: '/news/insert',
    categoriesRoute: '/categories',
    categoryDetailsRoute: '/categories/:categorySlug',
    categoryInsertRoute: '/categories/insert',
    informationRoute: '/information',
    shippingsRoute: '/shippings',
    shippingDetailsRoute: '/shippings/:shippingType',
    websiteRoute: '/website',
    languagesRoute: '/language',
    customersRoute: '/customer',
    paymentMethodsRoute: '/payment-method',
  };
  